version: '3'
services:
  backend:
    image: rahulv1996/flask-app:latest
    ports: 
      - "80:5000"
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "admin"
      MYSQL_DB: "mydb"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "mydb"
    ports:
      - "3306:3306"

    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
