apiVersion: v1
kind: Pod
metadata:
  name: flask-application
  labels:
    app: two-tier-app
spec:
  containers:
    - name: flask-ctr
      image: rahulv1996/flask-app:latest
      env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_DB
          value: "mydb"
      ports:
        - containerPort: 5000
      imagePullPolicy: Always
